services:
  app01:
    image: rinha:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "45MB"

  app02:
    image: rinha:latest
    ports:
      - "8082:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "45MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
      - app02
    ports:
      - "9999:9999"  
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "60MB"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgresql.conf:/etc/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "400MB"

networks:
  rinha:
    driver: bridge
